Cdt 824
genomicsengland/nhse_contractural_metrics pull request #1
Opened 2020-06-08 14:36 UTC by PlainB0b

I have added s005 ethnic category

2020-06-09 07:50 UTC, simonthompson99 requested changes
Hi Andrew - you've put this down as going into the value_string column, but actually because it's a categorical we should be writing it to the value_cid column. This will require creating a new ethnicity concept in the concept folder (there is already a file there but it has nonsense data in it so just overwrite it) with the values from concept table in genomic record (filter for codesystem_uri IN ('ethnicity') ). Have a look at https://github.com/genomicsengland/nhse_contractural_metrics/blob/master/metric/s001.py to see how this is done for gender.
Otherwise all looks good!
Simon.

2020-06-09 15:22 UTC, PlainB0b commented
Thanks @simonthompson99 
Do the values that populate the concept files have to be hard-coded?

2020-06-10 07:20 UTC, simonthompson99 commented
Yes @PlainB0b , they do because they need to be given the code that will be used for the representation in the final spreadsheet e.g. genomic record uses m/f but nhse want male/female so the concept table serves at a sort of look-up. If someone tries to add a line to the database where value_cid is null (because there is a concept code in genomic record which isn't in the ncm database) it will through an error as there is a constraint on the metric table that one and only one of the value_ columns can be non-null.
Do you think there is a better way?
Simon.

2020-06-25 15:52 UTC, PlainB0b commented
I've amended ethnic category to use value_cid and also added test urgency metric. Hope I'm doing this right :-)

2020-06-26 08:03 UTC, simonthompson99 reviewed
Getting there, but a few things to pick up on. Let me know if anything needs explaining. One other general thing that perhaps we should agree on is that, as much as possible, we should agree that when we make pull reviews the code runs and works (as much as we can tell anyhow). I think there are some syntax errors here that mean it wouldn't run. If we don't catch them in review then we're just introducing bugs which is, well, buggy.

2020-06-26 08:03 UTC, simonthompson99 commented on metric/s005.py
> +    q = s.query(gr.patient.uid.label('uid'),
think `gr.patient.uid` will need to be `gr.Patient.uid`, and strictly speaking we don't need the label bit for this row since the the column is already called `uid`. The label method is only needed when we want to rename the column i.e. when we want to do `select column_a as column_b`, without the label method the key used when the row is converted to a dictionary (using the `_asdict()` method on line 34) is the name of the column

2020-06-26 08:03 UTC, simonthompson99 commented on metric/s005.py
> +                gr.concept.concept_code.label('metric')
think `gr.concept.concept_code` needs to be `gr.Concept.concept_code`

2020-06-26 08:03 UTC, simonthompson99 commented on metric/s005.py
> +    'concept_code': 'ethnic_category',
can't quite work out whether this is actually required for everything to work out, but I think it would be good practice to have the concept_code for the metric match the codesystem of the concept it uses. i.e. if we're calling the _metric_ ethnic_category, then we should call the _codesystem_ that the value is referencing ethnic_category also. i.e. we should rename concept_data/ethnicity.py concept_data/ethnic_category.py. This applies to the test_urgency/priority bit too. Like I said, this may or may not be strictly required by the system, but we're going to get lots of metrics and concepts so it would make sense to try and allign as much as possible

2020-06-26 08:03 UTC, simonthompson99 commented on metric/s006.py
> +    'concept_code': 'test_urgency',
see other comment about concept_code:codesystem matching

2020-06-26 08:03 UTC, simonthompson99 commented on metric/s006.py
> +             gr.concept.uid)
metrics can be at a variety of levels, it doesn't always have to be at patient level. Test urgency is at the referral level so it makes sense to have the metric at referral level too rather than use referral participant.patient_uid which would introduce a lot of duplicate rows (since patients can be in multiple referrals), therefore...
```suggestion
    q = s.query(gr.Referral.uid,
                gr.Concept.concept_code.label('metric')
    ).\
    join(gr.concept,
             gr.referral.priority_cid ==
             gr.concept.uid)
```

2020-06-26 08:03 UTC, simonthompson99 commented on concept_data/metric.py
> +    ('ethnic_category', None)
the test urgency (i think i prefer this name over priority) metric needs to be added in here also, so...
```suggestion
    ('ethnic_category', None),
    ('test_urgency' None),
```

2020-07-03 14:36 UTC, simonthompson99 commented
Yep, looks good

2020-07-03 14:36 UTC, merged